# Generated by Django 5.1.3 on 2024-11-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admins",
            fields=[
                (
                    "id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=20)),
                ("prenom", models.CharField(max_length=70)),
                ("password", models.CharField(max_length=12)),
                ("birthdate", models.DateTimeField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
